apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java   
  template:
    metadata:
      name: my-pod
      labels:
        app: java     
    spec:
      containers:
      - name: my-container
        image: rashmimurthi/dev-app:latest   # replace with your Docker-image pushed on Dockerhub
        ports:
        - containerPort: 8080
